### ISSUE TITLE
IEFA question

### ISSUE THREAD

**Issue by BrianOBlanton** [mikebannis/parserasgeo#21]
Hi Mike,  this package is great.  I'm not a hydraulic person, rather a coastal oceanographer.  I develop a storm surge model, and we are interested in using some HEC-RAS data to help with designing our storm surge model grids.    All that to say that I am relatively unfamiliar with HEC model data.

A colleague gave me a g01 file, but prg.ParseRASGeo reports that: 
** Permanent Ineff= does not follow IEFA in geometry file. Aborting.  ** 

All I really need to do is get out the station elevations, mannings n, and the bank station numbers, without writing a parser since parserasgeo seems to be the solution I need. 

I'm not asking you to solve this for me, maybe just point in the right direction.    The g01 file is attached if you have a minute to look. 

Cheers,
Brian

[011003_NEW_RIVER.g01.txt](https://github.com/mikebannis/parserasgeo/files/4462315/011003_NEW_RIVER.g01.txt)

**Comment by mikebannis** [comment]
Brian,

If you don’t care about IEFA, the easiest approach would be to comment out the line that adds the iefa class (ineffective flow area) to the main cross section class. I think it’s in features/cross_section.py or similar. Then it should just ignore those lines. I haven’t touched the code in a bit and it might be out of date for newer versions of RAS. Let me know how it goes and good luck! PRG should be exactly what you need.

Mike Bannister
Researcher II-Software Development | Strategic Energy Analysis Center
National Renewable Energy Lab

15013 Denver West Parkway | Golden, CO 80401
303-275-3181 M: 404-434-5139

**Comment by BrianOBlanton** [comment]
that worked, Mike.  Also had to comment out the culvert stuff.

Thanks a billion.

Cheers,

[signature_577695696]

Brian O. Blanton, Ph.D.
Director of Earth Data Sciences
Oceanographer
Renaissance Computing Institute
University of North Carolina at Chapel Hill
100 Europa Drive
Suite 540 Chapel Hill, NC, 27517

Brian_Blanton@Renci.Org<mailto:Brian_Blanton@Renci.Org>
919-445-9620 (O)

[signature_1645074049]

________________________________

**Comment by mikebannis** [comment]
Good to hear! If you don’t mind, send me a link to the finished product at some point. I’d be curious to see what the code is getting used for.

Mike Bannister
Researcher II-Software Development | Strategic Energy Analysis Center
National Renewable Energy Lab

15013 Denver West Parkway | Golden, CO 80401
303-275-3181 M: 404-434-5139

**Comment by BrianOBlanton** [comment]
Will do, although my purpose is mundane compared to real hydraulics!

Cheers,

[signature_577695696]

Brian O. Blanton, Ph.D.
Director of Earth Data Sciences
Oceanographer
Renaissance Computing Institute
University of North Carolina at Chapel Hill
100 Europa Drive
Suite 540 Chapel Hill, NC, 27517

Brian_Blanton@Renci.Org<mailto:Brian_Blanton@Renci.Org>
919-445-9620 (O)

[signature_1645074049]

________________________________
