### ISSUE TITLE
XS Import Geo Question

### ISSUE THREAD

**Issue by lgrimley** [mikebannis/parserasgeo#23]
Hi Mike -- what can xs.import_geo(self, line, geo_file) be used for? I'm trying to georeference a few RAS models and was wondering if this might be relevant and how to use it (I'm trying to write geospatial info to the geometry file). Thanks!

**Comment by mikebannis** [comment]
Hi Lauren. I'm assuming you're refering to https://github.com/mikebannis/parserasgeo/blob/da968ef7c0a8a9e578e51f1f1704f224da2dfdb3/parserasgeo/features/cross_section.py#L494 or similar. That line is reading information from the RAS g01, g02, g0n files. 

The georeferencing is stored in https://github.com/mikebannis/parserasgeo/blob/da968ef7c0a8a9e578e51f1f1704f224da2dfdb3/parserasgeo/features/cross_section.py#L152-L155 and can be read or written via https://github.com/mikebannis/parserasgeo/blob/da968ef7c0a8a9e578e51f1f1704f224da2dfdb3/parserasgeo/features/cross_section.py#L473. 

Have fun!

**Comment by lgrimley** [comment]
Got it, thanks!!

**Comment by lgrimley** [comment]
Mike, I'm trying to read a RAS geometry file and get this error.

![Screen Shot 2021-03-10 at 10 54 22 AM](https://user-images.githubusercontent.com/40368514/110657734-13f40e00-818f-11eb-941e-9e397c9c2715.png)
